ALTER TABLE vets ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE specialties ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT TRUE NOT NULL;

CREATE TABLE IF NOT EXISTS account_guard (
  id INT PRIMARY KEY
);
INSERT INTO account_guard (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS accounts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL,
  active BOOLEAN DEFAULT TRUE NOT NULL,
  password_change_required BOOLEAN DEFAULT FALSE NOT NULL,
  owner_id INT NULL UNIQUE REFERENCES owners(id),
  failed_login_count INT DEFAULT 0 NOT NULL,
  locked_until TIMESTAMPTZ NULL,
  version BIGINT DEFAULT 0 NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_accounts_username ON accounts (username);

CREATE TABLE IF NOT EXISTS clinic_settings (
  id INT PRIMARY KEY,
  min_duration_minutes INT DEFAULT 15 NOT NULL,
  max_duration_minutes INT DEFAULT 120 NOT NULL,
  default_duration_minutes INT DEFAULT 30 NOT NULL,
  owner_booking_horizon_days INT DEFAULT 56 NOT NULL,
  staff_booking_horizon_days INT DEFAULT 365 NOT NULL,
  guided_hold_duration_minutes INT DEFAULT 5 NOT NULL,
  staff_offer_hold_duration_hours INT DEFAULT 24 NOT NULL,
  staff_claim_inactivity_minutes INT DEFAULT 30 NOT NULL,
  fallback_deadline_days INT DEFAULT 7 NOT NULL,
  sensitive_data_retention_days INT DEFAULT 30 NOT NULL,
  lockout_duration_minutes INT DEFAULT 15 NOT NULL,
  lockout_threshold INT DEFAULT 5 NOT NULL,
  zone_id VARCHAR(50) DEFAULT 'UTC' NOT NULL,
  morning_start_time TIME DEFAULT '08:00:00' NOT NULL,
  morning_end_time TIME DEFAULT '12:00:00' NOT NULL,
  afternoon_start_time TIME DEFAULT '12:00:00' NOT NULL,
  afternoon_end_time TIME DEFAULT '17:00:00' NOT NULL,
  evening_start_time TIME DEFAULT '17:00:00' NOT NULL,
  evening_end_time TIME DEFAULT '20:00:00' NOT NULL,
  urgent_care_guidance VARCHAR(1000) NOT NULL,
  emergency_phone VARCHAR(50) NOT NULL,
  version BIGINT DEFAULT 0 NOT NULL
);

INSERT INTO clinic_settings (
  id, min_duration_minutes, max_duration_minutes, default_duration_minutes,
  owner_booking_horizon_days, staff_booking_horizon_days,
  guided_hold_duration_minutes, staff_offer_hold_duration_hours, staff_claim_inactivity_minutes,
  fallback_deadline_days, sensitive_data_retention_days,
  lockout_duration_minutes, lockout_threshold,
  zone_id, morning_start_time, morning_end_time,
  afternoon_start_time, afternoon_end_time,
  evening_start_time, evening_end_time,
  urgent_care_guidance, emergency_phone, version
) VALUES (
  1, 15, 120, 30,
  56, 365,
  5, 24, 30,
  7, 30,
  15, 5,
  'UTC', '08:00:00', '12:00:00',
  '12:00:00', '17:00:00',
  '17:00:00', '20:00:00',
  'If your pet requires immediate medical attention, please visit the emergency clinic or call our urgent care line.',
  '608-555-0199', 0
) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS vet_schedules (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id INT NOT NULL REFERENCES vets(id),
  day_of_week INT NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  shift_type VARCHAR(20) DEFAULT 'REGULAR' NOT NULL,
  version BIGINT DEFAULT 0 NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_vet_schedules_vet_id ON vet_schedules (vet_id);

CREATE TABLE IF NOT EXISTS vet_schedule_exceptions (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id INT NOT NULL REFERENCES vets(id),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  start_time TIME NULL,
  end_time TIME NULL,
  exception_type VARCHAR(30) NOT NULL,
  reason VARCHAR(255) NULL,
  version BIGINT DEFAULT 0 NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_vet_schedule_exceptions_vet_id ON vet_schedule_exceptions (vet_id);

CREATE TABLE IF NOT EXISTS clinic_closures (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason VARCHAR(255) NULL,
  version BIGINT DEFAULT 0 NOT NULL
);

CREATE TABLE IF NOT EXISTS scheduling_requests (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id INT NOT NULL REFERENCES owners(id),
  pet_id INT NOT NULL REFERENCES pets(id),
  status VARCHAR(40) NOT NULL,
  original_text VARCHAR(2000) NULL,
  language VARCHAR(10) DEFAULT 'en' NOT NULL,
  urgent BOOLEAN DEFAULT FALSE NOT NULL,
  care_type VARCHAR(30) NULL,
  required_specialty_id INT NULL REFERENCES specialties(id),
  preferred_vet_id INT NULL REFERENCES vets(id),
  duration_minutes INT NULL,
  preferred_start_window TIMESTAMPTZ NULL,
  preferred_end_window TIMESTAMPTZ NULL,
  owner_horizon_end TIMESTAMPTZ NULL,
  first_queued_at TIMESTAMPTZ NULL,
  fallback_deadline TIMESTAMPTZ NULL,
  last_clarification_reason VARCHAR(255) NULL,
  clarification_count INT DEFAULT 0 NOT NULL,
  ai_summary VARCHAR(1000) NULL,
  full_ai_response TEXT NULL,
  retention_deadline TIMESTAMPTZ NULL,
  purged_at TIMESTAMPTZ NULL,
  consent_given_at TIMESTAMPTZ NULL,
  recovery_required BOOLEAN DEFAULT FALSE NOT NULL,
  version BIGINT DEFAULT 0 NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_requests_owner_id ON scheduling_requests (owner_id);
CREATE INDEX IF NOT EXISTS idx_requests_status ON scheduling_requests (status);

CREATE TABLE IF NOT EXISTS operations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token VARCHAR(100) NOT NULL UNIQUE,
  request_id INT NOT NULL REFERENCES scheduling_requests(id),
  operation_type VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL,
  dispatched_at TIMESTAMPTZ NOT NULL,
  deadline TIMESTAMPTZ NOT NULL,
  attempt_count INT DEFAULT 1 NOT NULL,
  version BIGINT DEFAULT 0 NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_operations_request_id ON operations (request_id);

CREATE TABLE IF NOT EXISTS reservations (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_type VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL,
  request_id INT NOT NULL REFERENCES scheduling_requests(id),
  owner_id INT NOT NULL REFERENCES owners(id),
  pet_id INT NOT NULL REFERENCES pets(id),
  vet_id INT NOT NULL REFERENCES vets(id),
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  version BIGINT DEFAULT 0 NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_reservations_request_id ON reservations (request_id);
CREATE INDEX IF NOT EXISTS idx_reservations_vet_time ON reservations (vet_id, start_time, end_time);

CREATE TABLE IF NOT EXISTS rejections (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id INT NOT NULL REFERENCES scheduling_requests(id),
  vet_id INT NOT NULL REFERENCES vets(id),
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  reason VARCHAR(255) NULL,
  rejected_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_rejections_request_id ON rejections (request_id);

CREATE TABLE IF NOT EXISTS staff_claims (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id INT NOT NULL UNIQUE REFERENCES scheduling_requests(id),
  staff_username VARCHAR(100) NOT NULL,
  claimed_at TIMESTAMPTZ NOT NULL,
  last_activity_at TIMESTAMPTZ NOT NULL,
  reclaimable_after TIMESTAMPTZ NOT NULL,
  version BIGINT DEFAULT 0 NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_staff_claims_staff_username ON staff_claims (staff_username);

CREATE TABLE IF NOT EXISTS appointments (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status VARCHAR(30) NOT NULL,
  request_id INT NULL REFERENCES scheduling_requests(id),
  owner_id INT NOT NULL REFERENCES owners(id),
  pet_id INT NOT NULL REFERENCES pets(id),
  vet_id INT NOT NULL REFERENCES vets(id),
  care_type VARCHAR(30) NOT NULL,
  required_specialty_id INT NULL REFERENCES specialties(id),
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  booking_source VARCHAR(30) NOT NULL,
  offline_reason VARCHAR(255) NULL,
  cancellation_reason VARCHAR(255) NULL,
  completed_at TIMESTAMPTZ NULL,
  completion_notes VARCHAR(1000) NULL,
  visit_id INT NULL REFERENCES visits(id),
  version BIGINT DEFAULT 0 NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_appointments_owner_id ON appointments (owner_id);
CREATE INDEX IF NOT EXISTS idx_appointments_vet_time ON appointments (vet_id, start_time, end_time);

CREATE TABLE IF NOT EXISTS calendar_conflicts (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id INT NOT NULL REFERENCES appointments(id),
  vet_id INT NOT NULL REFERENCES vets(id),
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  conflict_type VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL,
  detected_at TIMESTAMPTZ NOT NULL,
  resolved_at TIMESTAMPTZ NULL,
  version BIGINT DEFAULT 0 NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_conflicts_appointment_id ON calendar_conflicts (appointment_id);

CREATE TABLE IF NOT EXISTS notifications (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id INT NOT NULL REFERENCES owners(id),
  title_key VARCHAR(100) NOT NULL,
  message_key VARCHAR(100) NOT NULL,
  message_params VARCHAR(500) NULL,
  target_url VARCHAR(255) NULL,
  is_read BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_notifications_owner_id ON notifications (owner_id, is_read);

CREATE TABLE IF NOT EXISTS audit_records (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type VARCHAR(50) NOT NULL,
  actor_username VARCHAR(100) NOT NULL,
  actor_role VARCHAR(20) NOT NULL,
  target_entity_type VARCHAR(50) NOT NULL,
  target_entity_id VARCHAR(50) NOT NULL,
  reason_code VARCHAR(50) NULL,
  metadata_json TEXT NULL,
  occurred_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_occurred_at ON audit_records (occurred_at);
CREATE INDEX IF NOT EXISTS idx_audit_target ON audit_records (target_entity_type, target_entity_id);
