/*
 * Copyright 2012-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.samples.petclinic.system;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.UUID;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.FlywayException;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;

class FlywayMigrationTests {

	private JdbcDataSource createDataSource() {
		JdbcDataSource ds = new JdbcDataSource();
		ds.setURL("jdbc:h2:mem:flyway_test_" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1");
		ds.setUser("sa");
		ds.setPassword("");
		return ds;
	}

	@Test
	void testFreshDatabaseMigration() throws Exception {
		JdbcDataSource ds = createDataSource();
		Flyway flyway = Flyway.configure()
			.dataSource(ds)
			.locations("classpath:db/migration/h2")
			.baselineOnMigrate(false)
			.load();

		flyway.migrate();

		try (Connection conn = ds.getConnection(); Statement stmt = conn.createStatement()) {
			try (ResultSet rs = stmt.executeQuery("SELECT count(*) FROM vets")) {
				assertThat(rs.next()).isTrue();
				assertThat(rs.getInt(1)).isEqualTo(6);
			}
			try (ResultSet rs = stmt.executeQuery("SELECT count(*) FROM owners")) {
				assertThat(rs.next()).isTrue();
				assertThat(rs.getInt(1)).isEqualTo(10);
			}
			try (ResultSet rs = stmt.executeQuery("SELECT count(*) FROM pets")) {
				assertThat(rs.next()).isTrue();
				assertThat(rs.getInt(1)).isEqualTo(13);
			}
			try (ResultSet rs = stmt.executeQuery("SELECT count(*) FROM clinic_settings")) {
				assertThat(rs.next()).isTrue();
				assertThat(rs.getInt(1)).isEqualTo(1);
			}
			try (ResultSet rs = stmt.executeQuery("SELECT count(*) FROM account_guard")) {
				assertThat(rs.next()).isTrue();
				assertThat(rs.getInt(1)).isEqualTo(1);
			}
			try (ResultSet rs = stmt.executeQuery("SELECT count(*) FROM request_availability_windows")) {
				assertThat(rs.next()).isTrue();
				assertThat(rs.getInt(1)).isZero();
			}
			try (ResultSet rs = stmt.executeQuery("SELECT count(*) FROM request_availability_intervals")) {
				assertThat(rs.next()).isTrue();
				assertThat(rs.getInt(1)).isZero();
			}
		}
	}

	@Test
	void testExplicitlyBaselinedLegacySchemaMigratesToScheduling() throws Exception {
		JdbcDataSource ds = createDataSource();

		// Run legacy DDL/data directly
		try (Connection conn = ds.getConnection(); Statement stmt = conn.createStatement()) {
			stmt.execute(
					"CREATE TABLE vets (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, first_name VARCHAR(30), last_name VARCHAR(30));");
			stmt.execute(
					"CREATE TABLE specialties (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(80));");
			stmt.execute("CREATE TABLE vet_specialties (vet_id INTEGER NOT NULL, specialty_id INTEGER NOT NULL);");
			stmt.execute(
					"CREATE TABLE types (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(80));");
			stmt.execute(
					"CREATE TABLE owners (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, first_name VARCHAR(30), last_name VARCHAR(30), address VARCHAR(255), city VARCHAR(80), telephone VARCHAR(20));");
			stmt.execute(
					"CREATE TABLE pets (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(30), birth_date DATE, type_id INTEGER NOT NULL, owner_id INTEGER);");
			stmt.execute(
					"CREATE TABLE visits (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, pet_id INTEGER, visit_date DATE, description VARCHAR(255));");
			stmt.execute("INSERT INTO vets (first_name, last_name) VALUES ('James', 'Carter');");
		}

		Flyway flyway = Flyway.configure()
			.dataSource(ds)
			.locations("classpath:db/migration/h2")
			.baselineVersion("1")
			.baselineDescription("legacy baseline")
			.baselineOnMigrate(false)
			.load();

		flyway.baseline();
		flyway.migrate();

		try (Connection conn = ds.getConnection(); Statement stmt = conn.createStatement()) {
			try (ResultSet rs = stmt.executeQuery("SELECT active FROM vets WHERE id=1")) {
				assertThat(rs.next()).isTrue();
				assertThat(rs.getBoolean(1)).isTrue();
			}
			try (ResultSet rs = stmt.executeQuery("SELECT count(*) FROM clinic_settings")) {
				assertThat(rs.next()).isTrue();
				assertThat(rs.getInt(1)).isEqualTo(1);
			}
		}
	}

	@Test
	void testExistingNotificationMessageKeysAreNormalized() throws Exception {
		JdbcDataSource ds = createDataSource();
		Flyway flywayToV3 = Flyway.configure().dataSource(ds).locations("classpath:db/migration/h2").target("3").load();
		flywayToV3.migrate();

		try (Connection conn = ds.getConnection(); Statement stmt = conn.createStatement()) {
			stmt.executeUpdate(
					"INSERT INTO notifications " + "(owner_id, title_key, message_key, is_read, created_at) VALUES "
							+ "(1, 'notification.appointment.confirmed.title', "
							+ "'notification.appointment.confirmed.message', FALSE, CURRENT_TIMESTAMP)");
			stmt.executeUpdate(
					"INSERT INTO notifications " + "(owner_id, title_key, message_key, is_read, created_at) VALUES "
							+ "(1, 'notification.staff.offer.title', "
							+ "'notification.staff.offer.message', FALSE, CURRENT_TIMESTAMP)");
		}

		Flyway.configure().dataSource(ds).locations("classpath:db/migration/h2").load().migrate();

		try (Connection conn = ds.getConnection();
				Statement stmt = conn.createStatement();
				ResultSet rs = stmt.executeQuery("SELECT title_key, message_key FROM notifications ORDER BY id")) {
			assertThat(rs.next()).isTrue();
			assertThat(rs.getString("title_key")).isEqualTo("notification.appointmentConfirmed.title");
			assertThat(rs.getString("message_key")).isEqualTo("notification.appointmentConfirmed.message");
			assertThat(rs.next()).isTrue();
			assertThat(rs.getString("title_key")).isEqualTo("notification.staffOffer.title");
			assertThat(rs.getString("message_key")).isEqualTo("notification.staffOffer.message");
			assertThat(rs.next()).isFalse();
		}
	}

	@Test
	void testUnknownNonEmptySchemaFailsWithoutBaseline() throws Exception {
		JdbcDataSource ds = createDataSource();

		try (Connection conn = ds.getConnection(); Statement stmt = conn.createStatement()) {
			stmt.execute("CREATE TABLE unknown_custom_table (id INT PRIMARY KEY);");
		}

		Flyway flyway = Flyway.configure()
			.dataSource(ds)
			.locations("classpath:db/migration/h2")
			.baselineOnMigrate(false)
			.load();

		assertThatThrownBy(flyway::migrate).isInstanceOf(FlywayException.class);
	}

}
