ALTER TABLE vets ADD COLUMN active BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE specialties ADD COLUMN active BOOLEAN DEFAULT TRUE NOT NULL;

CREATE TABLE account_guard (
  id INTEGER PRIMARY KEY
);
INSERT INTO account_guard (id) VALUES (1);

CREATE TABLE accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL,
  active BOOLEAN DEFAULT TRUE NOT NULL,
  password_change_required BOOLEAN DEFAULT FALSE NOT NULL,
  owner_id INTEGER,
  failed_login_count INTEGER DEFAULT 0 NOT NULL,
  locked_until TIMESTAMP,
  version BIGINT DEFAULT 0 NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);
ALTER TABLE accounts ADD CONSTRAINT uc_accounts_username UNIQUE (username);
ALTER TABLE accounts ADD CONSTRAINT uc_accounts_owner_id UNIQUE (owner_id);
ALTER TABLE accounts ADD CONSTRAINT fk_accounts_owners FOREIGN KEY (owner_id) REFERENCES owners (id);
CREATE INDEX idx_accounts_username ON accounts (username);

CREATE TABLE clinic_settings (
  id INTEGER PRIMARY KEY,
  min_duration_minutes INTEGER DEFAULT 15 NOT NULL,
  max_duration_minutes INTEGER DEFAULT 120 NOT NULL,
  default_duration_minutes INTEGER DEFAULT 30 NOT NULL,
  owner_booking_horizon_days INTEGER DEFAULT 56 NOT NULL,
  staff_booking_horizon_days INTEGER DEFAULT 365 NOT NULL,
  guided_hold_duration_minutes INTEGER DEFAULT 5 NOT NULL,
  staff_offer_hold_duration_hours INTEGER DEFAULT 24 NOT NULL,
  staff_claim_inactivity_minutes INTEGER DEFAULT 30 NOT NULL,
  fallback_deadline_days INTEGER DEFAULT 7 NOT NULL,
  sensitive_data_retention_days INTEGER DEFAULT 30 NOT NULL,
  lockout_duration_minutes INTEGER DEFAULT 15 NOT NULL,
  lockout_threshold INTEGER DEFAULT 5 NOT NULL,
  zone_id VARCHAR(50) DEFAULT 'UTC' NOT NULL,
  morning_start_time TIME DEFAULT '08:00:00' NOT NULL,
  morning_end_time TIME DEFAULT '12:00:00' NOT NULL,
  afternoon_start_time TIME DEFAULT '12:00:00' NOT NULL,
  afternoon_end_time TIME DEFAULT '17:00:00' NOT NULL,
  evening_start_time TIME DEFAULT '17:00:00' NOT NULL,
  evening_end_time TIME DEFAULT '20:00:00' NOT NULL,
  urgent_care_guidance VARCHAR(1000) NOT NULL,
  emergency_phone VARCHAR(50) NOT NULL,
  version BIGINT DEFAULT 0 NOT NULL
);

INSERT INTO clinic_settings (
  id, min_duration_minutes, max_duration_minutes, default_duration_minutes,
  owner_booking_horizon_days, staff_booking_horizon_days,
  guided_hold_duration_minutes, staff_offer_hold_duration_hours, staff_claim_inactivity_minutes,
  fallback_deadline_days, sensitive_data_retention_days,
  lockout_duration_minutes, lockout_threshold,
  zone_id, morning_start_time, morning_end_time,
  afternoon_start_time, afternoon_end_time,
  evening_start_time, evening_end_time,
  urgent_care_guidance, emergency_phone, version
) VALUES (
  1, 15, 120, 30,
  56, 365,
  5, 24, 30,
  7, 30,
  15, 5,
  'UTC', '08:00:00', '12:00:00',
  '12:00:00', '17:00:00',
  '17:00:00', '20:00:00',
  'If your pet requires immediate medical attention, please visit the emergency clinic or call our urgent care line.',
  '608-555-0199', 0
);

CREATE TABLE vet_schedules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id INTEGER NOT NULL,
  day_of_week INTEGER NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  shift_type VARCHAR(20) DEFAULT 'REGULAR' NOT NULL,
  version BIGINT DEFAULT 0 NOT NULL
);
ALTER TABLE vet_schedules ADD CONSTRAINT fk_vet_schedules_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
CREATE INDEX idx_vet_schedules_vet_id ON vet_schedules (vet_id);

CREATE TABLE vet_schedule_exceptions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vet_id INTEGER NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  start_time TIME,
  end_time TIME,
  exception_type VARCHAR(30) NOT NULL,
  reason VARCHAR(255),
  version BIGINT DEFAULT 0 NOT NULL
);
ALTER TABLE vet_schedule_exceptions ADD CONSTRAINT fk_vet_schedule_exceptions_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
CREATE INDEX idx_vet_schedule_exceptions_vet_id ON vet_schedule_exceptions (vet_id);

CREATE TABLE clinic_closures (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason VARCHAR(255),
  version BIGINT DEFAULT 0 NOT NULL
);

CREATE TABLE scheduling_requests (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id INTEGER NOT NULL,
  pet_id INTEGER NOT NULL,
  status VARCHAR(40) NOT NULL,
  original_text VARCHAR(2000),
  language VARCHAR(10) DEFAULT 'en' NOT NULL,
  urgent BOOLEAN DEFAULT FALSE NOT NULL,
  care_type VARCHAR(30),
  required_specialty_id INTEGER,
  preferred_vet_id INTEGER,
  duration_minutes INTEGER,
  preferred_start_window TIMESTAMP,
  preferred_end_window TIMESTAMP,
  owner_horizon_end TIMESTAMP,
  first_queued_at TIMESTAMP,
  fallback_deadline TIMESTAMP,
  last_clarification_reason VARCHAR(255),
  clarification_count INTEGER DEFAULT 0 NOT NULL,
  ai_summary VARCHAR(1000),
  full_ai_response TEXT,
  retention_deadline TIMESTAMP,
  purged_at TIMESTAMP,
  consent_given_at TIMESTAMP,
  recovery_required BOOLEAN DEFAULT FALSE NOT NULL,
  version BIGINT DEFAULT 0 NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);
ALTER TABLE scheduling_requests ADD CONSTRAINT fk_requests_owners FOREIGN KEY (owner_id) REFERENCES owners (id);
ALTER TABLE scheduling_requests ADD CONSTRAINT fk_requests_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
ALTER TABLE scheduling_requests ADD CONSTRAINT fk_requests_specialties FOREIGN KEY (required_specialty_id) REFERENCES specialties (id);
ALTER TABLE scheduling_requests ADD CONSTRAINT fk_requests_vets FOREIGN KEY (preferred_vet_id) REFERENCES vets (id);
CREATE INDEX idx_requests_owner_id ON scheduling_requests (owner_id);
CREATE INDEX idx_requests_status ON scheduling_requests (status);

CREATE TABLE operations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token VARCHAR(100) NOT NULL,
  request_id INTEGER NOT NULL,
  operation_type VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL,
  dispatched_at TIMESTAMP NOT NULL,
  deadline TIMESTAMP NOT NULL,
  attempt_count INTEGER DEFAULT 1 NOT NULL,
  version BIGINT DEFAULT 0 NOT NULL
);
ALTER TABLE operations ADD CONSTRAINT uc_operations_token UNIQUE (token);
ALTER TABLE operations ADD CONSTRAINT fk_operations_requests FOREIGN KEY (request_id) REFERENCES scheduling_requests (id);
CREATE INDEX idx_operations_request_id ON operations (request_id);

CREATE TABLE reservations (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_type VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL,
  request_id INTEGER NOT NULL,
  owner_id INTEGER NOT NULL,
  pet_id INTEGER NOT NULL,
  vet_id INTEGER NOT NULL,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  version BIGINT DEFAULT 0 NOT NULL,
  created_at TIMESTAMP NOT NULL
);
ALTER TABLE reservations ADD CONSTRAINT fk_reservations_requests FOREIGN KEY (request_id) REFERENCES scheduling_requests (id);
ALTER TABLE reservations ADD CONSTRAINT fk_reservations_owners FOREIGN KEY (owner_id) REFERENCES owners (id);
ALTER TABLE reservations ADD CONSTRAINT fk_reservations_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
ALTER TABLE reservations ADD CONSTRAINT fk_reservations_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
CREATE INDEX idx_reservations_request_id ON reservations (request_id);
CREATE INDEX idx_reservations_vet_time ON reservations (vet_id, start_time, end_time);

CREATE TABLE rejections (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id INTEGER NOT NULL,
  vet_id INTEGER NOT NULL,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  reason VARCHAR(255),
  rejected_at TIMESTAMP NOT NULL
);
ALTER TABLE rejections ADD CONSTRAINT fk_rejections_requests FOREIGN KEY (request_id) REFERENCES scheduling_requests (id);
ALTER TABLE rejections ADD CONSTRAINT fk_rejections_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
CREATE INDEX idx_rejections_request_id ON rejections (request_id);

CREATE TABLE staff_claims (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id INTEGER NOT NULL,
  staff_username VARCHAR(100) NOT NULL,
  claimed_at TIMESTAMP NOT NULL,
  last_activity_at TIMESTAMP NOT NULL,
  reclaimable_after TIMESTAMP NOT NULL,
  version BIGINT DEFAULT 0 NOT NULL
);
ALTER TABLE staff_claims ADD CONSTRAINT uc_staff_claims_request_id UNIQUE (request_id);
ALTER TABLE staff_claims ADD CONSTRAINT fk_staff_claims_requests FOREIGN KEY (request_id) REFERENCES scheduling_requests (id);
CREATE INDEX idx_staff_claims_staff_username ON staff_claims (staff_username);

CREATE TABLE appointments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status VARCHAR(30) NOT NULL,
  request_id INTEGER,
  owner_id INTEGER NOT NULL,
  pet_id INTEGER NOT NULL,
  vet_id INTEGER NOT NULL,
  care_type VARCHAR(30) NOT NULL,
  required_specialty_id INTEGER,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  booking_source VARCHAR(30) NOT NULL,
  offline_reason VARCHAR(255),
  cancellation_reason VARCHAR(255),
  completed_at TIMESTAMP,
  completion_notes VARCHAR(1000),
  visit_id INTEGER,
  version BIGINT DEFAULT 0 NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL
);
ALTER TABLE appointments ADD CONSTRAINT fk_appointments_requests FOREIGN KEY (request_id) REFERENCES scheduling_requests (id);
ALTER TABLE appointments ADD CONSTRAINT fk_appointments_owners FOREIGN KEY (owner_id) REFERENCES owners (id);
ALTER TABLE appointments ADD CONSTRAINT fk_appointments_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
ALTER TABLE appointments ADD CONSTRAINT fk_appointments_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
ALTER TABLE appointments ADD CONSTRAINT fk_appointments_specialties FOREIGN KEY (required_specialty_id) REFERENCES specialties (id);
ALTER TABLE appointments ADD CONSTRAINT fk_appointments_visits FOREIGN KEY (visit_id) REFERENCES visits (id);
CREATE INDEX idx_appointments_owner_id ON appointments (owner_id);
CREATE INDEX idx_appointments_vet_time ON appointments (vet_id, start_time, end_time);

CREATE TABLE calendar_conflicts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  appointment_id INTEGER NOT NULL,
  vet_id INTEGER NOT NULL,
  start_time TIMESTAMP NOT NULL,
  end_time TIMESTAMP NOT NULL,
  conflict_type VARCHAR(30) NOT NULL,
  status VARCHAR(30) NOT NULL,
  detected_at TIMESTAMP NOT NULL,
  resolved_at TIMESTAMP,
  version BIGINT DEFAULT 0 NOT NULL
);
ALTER TABLE calendar_conflicts ADD CONSTRAINT fk_conflicts_appointments FOREIGN KEY (appointment_id) REFERENCES appointments (id);
ALTER TABLE calendar_conflicts ADD CONSTRAINT fk_conflicts_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
CREATE INDEX idx_conflicts_appointment_id ON calendar_conflicts (appointment_id);

CREATE TABLE notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id INTEGER NOT NULL,
  title_key VARCHAR(100) NOT NULL,
  message_key VARCHAR(100) NOT NULL,
  message_params VARCHAR(500),
  target_url VARCHAR(255),
  is_read BOOLEAN DEFAULT FALSE NOT NULL,
  created_at TIMESTAMP NOT NULL
);
ALTER TABLE notifications ADD CONSTRAINT fk_notifications_owners FOREIGN KEY (owner_id) REFERENCES owners (id);
CREATE INDEX idx_notifications_owner_id ON notifications (owner_id, is_read);

CREATE TABLE audit_records (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type VARCHAR(50) NOT NULL,
  actor_username VARCHAR(100) NOT NULL,
  actor_role VARCHAR(20) NOT NULL,
  target_entity_type VARCHAR(50) NOT NULL,
  target_entity_id VARCHAR(50) NOT NULL,
  reason_code VARCHAR(50),
  metadata_json TEXT,
  occurred_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_audit_occurred_at ON audit_records (occurred_at);
CREATE INDEX idx_audit_target ON audit_records (target_entity_type, target_entity_id);
